version: '3.8'
services:
  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27018:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - shared-mongo
volumes:
  mysql-data:
  mongodb-data:
networks:
  shared-mongo:
    driver: bridge
    name: shared-mongo
